import { int, mysqlEnum, mysqlTable, text, timestamp, varchar } from "drizzle-orm/mysql-core";

/**
 * Core user table backing auth flow.
 * Extend this file with additional tables as your product grows.
 * Columns use camelCase to match both database fields and generated types.
 */
export const users = mysqlTable("users", {
  /**
   * Surrogate primary key. Auto-incremented numeric value managed by the database.
   * Use this for relations between tables.
   */
  id: int("id").autoincrement().primaryKey(),
  /** Manus OAuth identifier (openId) returned from the OAuth callback. Unique per user. */
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/**
 * Lotteries table - stores information about different lotteries
 */
export const lotteries = mysqlTable("lotteries", {
  id: int("id").autoincrement().primaryKey(),
  name: varchar("name", { length: 64 }).notNull(), // e.g., "Mega Sena", "Quina"
  description: text("description"),
  totalNumbers: int("totalNumbers").notNull(), // e.g., 60 for Mega Sena
  numbersPerDraw: int("numbersPerDraw").notNull(), // e.g., 6 for Mega Sena
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type Lottery = typeof lotteries.$inferSelect;
export type InsertLottery = typeof lotteries.$inferInsert;

/**
 * Draws table - stores results of lottery draws
 */
export const draws = mysqlTable("draws", {
  id: int("id").autoincrement().primaryKey(),
  lotteryId: int("lotteryId").notNull(),
  drawNumber: int("drawNumber").notNull(), // e.g., 2736 for Mega Sena
  numbers: text("numbers").notNull(), // JSON array of numbers
  drawDate: timestamp("drawDate").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type Draw = typeof draws.$inferSelect;
export type InsertDraw = typeof draws.$inferInsert;

/**
 * AI Strategies table - stores 18+ strategies with weights and performance
 */
export const aiStrategies = mysqlTable("aiStrategies", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  lotteryId: int("lotteryId").notNull(),
  strategyName: varchar("strategyName", { length: 128 }).notNull(),
  description: text("description"),
  weight: int("weight").default(100).notNull(), // 0-100 scale
  accuracy: int("accuracy").default(0).notNull(), // percentage
  totalPredictions: int("totalPredictions").default(0).notNull(),
  correctPredictions: int("correctPredictions").default(0).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type AIStrategy = typeof aiStrategies.$inferSelect;
export type InsertAIStrategy = typeof aiStrategies.$inferInsert;

/**
 * AI Suggestions table - stores suggestions generated by AI for upcoming draws
 */
export const aiSuggestions = mysqlTable("aiSuggestions", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  lotteryId: int("lotteryId").notNull(),
  drawNumber: int("drawNumber"),
  suggestedNumbers: text("suggestedNumbers").notNull(), // JSON array
  confidence: int("confidence").notNull(), // 0-100
  strategyBreakdown: text("strategyBreakdown").notNull(), // JSON object with strategy contributions
  actualNumbers: text("actualNumbers"), // JSON array - filled after draw
  matches: int("matches").default(0), // number of correct predictions
  generatedAt: timestamp("generatedAt").defaultNow().notNull(),
  drawnAt: timestamp("drawnAt"),
});

export type AISuggestion = typeof aiSuggestions.$inferSelect;
export type InsertAISuggestion = typeof aiSuggestions.$inferInsert;

/**
 * User Bets table - stores personal bets saved by users
 */
export const userBets = mysqlTable("userBets", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  lotteryId: int("lotteryId").notNull(),
  drawNumber: int("drawNumber"),
  betNumbers: text("betNumbers").notNull(), // JSON array
  amount: int("amount").notNull(), // in cents
  status: mysqlEnum("status", ["pending", "won", "lost"]).default("pending").notNull(),
  matches: int("matches").default(0),
  prize: int("prize").default(0), // in cents
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  drawnAt: timestamp("drawnAt"),
});

export type UserBet = typeof userBets.$inferSelect;
export type InsertUserBet = typeof userBets.$inferInsert;

/**
 * User Wallet table - tracks financial data for each user
 */
export const userWallet = mysqlTable("userWallet", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull().unique(),
  totalSpent: int("totalSpent").default(0).notNull(), // in cents
  totalWon: int("totalWon").default(0).notNull(), // in cents
  netProfit: int("netProfit").default(0).notNull(), // in cents
  roi: int("roi").default(0).notNull(), // percentage
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type UserWallet = typeof userWallet.$inferSelect;
export type InsertUserWallet = typeof userWallet.$inferInsert;

/**
 * User Alerts table - stores personalized alert configurations
 */
export const userAlerts = mysqlTable("userAlerts", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  lotteryId: int("lotteryId").notNull(),
  alertType: mysqlEnum("alertType", ["critical_delay", "accumulated_prize", "hot_numbers"]).notNull(),
  threshold: int("threshold"), // e.g., delay > 50 draws
  enabled: int("enabled").default(1).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type UserAlert = typeof userAlerts.$inferSelect;
export type InsertUserAlert = typeof userAlerts.$inferInsert;

/**
 * AI Training Log table - tracks the evolution of AI strategy weights
 */
export const aiTrainingLog = mysqlTable("aiTrainingLog", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  strategyId: int("strategyId").notNull(),
  previousWeight: int("previousWeight").notNull(),
  newWeight: int("newWeight").notNull(),
  reason: varchar("reason", { length: 256 }),
  accuracy: int("accuracy").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type AITrainingLog = typeof aiTrainingLog.$inferSelect;
export type InsertAITrainingLog = typeof aiTrainingLog.$inferInsert;